#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 2 of the License, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.

set -e
set -u

# Whether to disable the wifi when going onto the docking station.
disable_wifi=true

# Find the user who is currently logged in on the primary screen.
user="$(who -u | grep -F '(:0)' | head -n 1 | awk '{print $1}')"

logger -t think-dock -- "Using user $user."

case "$1" in
	on)
		setto=on

		# Disable the wireless connection, if the user specified the option,
		# the ``nmcli`` tool is available and the computer is actually
		# connected to the ethernet.
		# HACK This is done here, since it does not work from within
		# ``think-dock`` when it is called via this script here.
		if [[ "$disable_wifi" = "true" ]] \
			&& type nmcli > /dev/null 2>&1 \
			&& [[ "$(cat "/sys/class/net/eth0/carrier")" = 1 ]]
		then
			nmcli nm wifi off
		fi
		;;
	off)
		setto=off

		# Enable the wireless connection.
		# HACK This is done here, since it does not work from within
		# ``think-dock`` when it is called via this script here.
		if [[ "$disable_wifi" = "true" ]] && type nmcli > /dev/null 2>&1
		then
			nmcli nm wifi on
		fi
		;;
esac

su -c "DISPLAY=:0.0 /usr/bin/think-dock $setto" --login "$user" &

disown
